apiVersion: v1
kind: Service
metadata:
  name: model-registry-ui-service
spec:
  selector:
    app: model-registry-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
